version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    build:
      context: ./db
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./frontend/nginx/conf
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
