name: Backup Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
              
      - name: Make backup.sh executable
        run: chmod +x backup.sh

      - name: Setup environment variables and run backup script
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_actions
          chmod 600 ~/.ssh/id_rsa_actions
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa_actions
          ./backup.sh --max-backups 1

      - name: Archive backup to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backup-archive
          path: ~/backup/*.tar.gz
          if-no-files-found: warn
        env:
          retention-days: 5

      - name: Upload versions JSON to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: versions-json
          path: ~/backup/versions.json
          if-no-files-found: warn
        env:
          retention-days: 5
