name: Backend Pipeline

on:
  push:
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check lint with flake8
        run: |
          cd app
          pip install flake8
          flake8

      - name: Run tests with pytest
        run: |
          cd app
          pip install --no-cache-dir -r requirements_dev.txt
          pytest tests/

      - name: Build Docker image
        run: |
          cd app
          docker build -t be_devops:latest .

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        run: |
          docker tag be_devops:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend-image:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend-image:latest
      
      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-image
          path: .
        env:
          retention-days: 1
