name: Deploy Application

on:
  push:
    branches:
      - DO_5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Connect to VM via SSH
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.SSH_EC2_HOST }}
        username: ${{ secrets.SSH_EC2_USERNAME }}
        key: ${{ secrets.SSH_EC2_PRIVATE_KEY_PEM }}
        port: ${{ secrets.SSH_EC2_PORT }}
        script: |
          docker-compose -f docker-compose-prod.yml up -d

    # - name: Connect to VM via SSH and pull
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_EC2_PRIVATE_KEY_PEM }}" > ~/.ssh/ssh-action.pem
    #     chmod 600 ~/.ssh/ssh-action.pem
    #     ssh-keyscan -H ${{ secrets.SSH_EC2_HOST }} > ~/.ssh/know_hosts
    #     ssh -i "~/.ssh/ssh-action.pem" ${{ secrets.SSH_EC2_USERNAME }}@${{ secrets.SSH_EC2_HOST }} "docker-compose -f docker-compose-prod.yml up -d && exit"

    # - name: Test application availability
    #   run: |
    #     # Add your test commands here to verify the application is accessible over the internet
