name: Deploy Application

on:
  push:
    branches:
      - DO_5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Connect to VM via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_EC2_HOST }}
        username: ${{ secrets.SSH_EC2_USERNAME }}
        key: ${{ secrets.SSH_EC2_PRIVATE_KEY_PEM }}
        port: ${{ secrets.SSH_EC2_PORT }}

    - name: Install aws cli
      run: sudo apt install awscli -y

    - name: Configure aws credential
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Pull and up docker images from private registry
      run: |
        export  AWS_REGION=${{ secrets.AWS_REGION }}
        export  AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
        export  DB_USER=${{ secrets.DB_USER }}
        export  DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        export  DB_ENDPOINT=${{ secrets.DB_ENDPOINT }}
        export  DB_NAME=${{ secrets.DB_NAME }}
        export  POSTGRES_HOST_AUTH_METHOD=${{ secrets.POSTGRES_HOST_AUTH_METHOD }}
        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
        docker-compose -f docker-compose-prod.yaml up -d

    # - name: Test application availability
    #   run: |
    #     # Add your test commands here to verify the application is accessible over the internet
