name: Frontend Pipeline

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install chromium-browser
        run: sudo apt-get update && sudo apt-get install chromium-browser -y

      - name: Change directory to frontend
        run: cd frontend && npm install

      - name: Check lint
        run: cd frontend && npm run lint

      - name: Run tests
        run: |
          cd frontend
          npm ci
          npm run test:ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flameflashy-intern
          IMAGE_TAG: fe_devops
        run: |
          cd frontend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - name: Save Docker image as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: fe_devops_image
      #     path: .
      #   env:
      #     retention-days: 1
